Tridy dedicnost
CvetelinaS/pyladies pull request #3
Opened 2019-04-29 08:52 UTC by CvetelinaS

Nový domácí úkol je cars.py. Z min. týdne je šibenice, ale nemám k tomu ko´mentáře, nevím zda jsi to tehdy viděl.

2019-05-02 07:39 UTC, rusinsky-pavel requested changes

2019-05-02 07:39 UTC, rusinsky-pavel commented on 06/sibenice.py
> +    print (str(zivoty))
Mezera, při printování nemusíš mít string

2019-05-02 07:39 UTC, rusinsky-pavel commented on 06/sibenice.py
> +    print (str(zivoty))
Ty mezery u printu máš všude.. Při volání funkce nejsou potřeba

2019-05-02 07:39 UTC, rusinsky-pavel commented on 06/sibenice_util.py
> +wordlist=["boy","man","kid","worm","word","disk",
Proč existuje util soubor, pokud není nikde importovaný?

2019-05-02 07:39 UTC, rusinsky-pavel commented on 06/test_vyhodnot.py
> +    '''if  'xxx' in radek:
Proč je toto celé komentář?

2019-05-02 07:39 UTC, rusinsky-pavel commented on cars.py
> +        self.max_speed
Co mělo toto dělat?

2019-05-02 07:39 UTC, rusinsky-pavel commented on cars.py
> +        self.max_speed
Co mělo toto dělat?

2019-05-02 07:39 UTC, rusinsky-pavel commented on cars.py
> +class Porsche(Car):
Proč inheritance, když nepoužíváš nic z parent class?

2019-05-02 07:39 UTC, rusinsky-pavel commented on cars.py
> +        break
Podle PEP8 musí být newline na konci

2019-05-02 07:39 UTC, rusinsky-pavel commented on hra_trida.py
> +
Toto si chtěla odevzdávat?

2019-05-27 11:26 UTC, CvetelinaS commented on 06/sibenice_util.py
> +wordlist=["boy","man","kid","worm","word","disk",
Protože jsem si ho udělala, když jsem nad sibhenici zacala pracovat a potom jsem změnila postup. Tady jsem nechtěně nahrála spousta souborů, které jsem musela smazat, ale už bhylo pozdě, protože jsem je nahrála sem. Vím, že je tady zmatek. Promiň!

2019-05-27 11:26 UTC, CvetelinaS commented on cars.py
> +class Porsche(Car):
Používám max_speed a "brands" jsem chtěla mít jako jména zvířátek u příkladů z lekce.

2019-06-06 11:29 UTC, closed without merging